### ISSUE TITLE
More detail on usage in Main vs Renderer processes

### ISSUE THREAD

**Issue by naheller** [sindresorhus/electron-config#10]
I am using Electron and React to create a web app, and the documentation for electron-config does not show how to carry out IPC (inter-process communication) between processes.

In the case of React, the render process would be a component. How do I use electron-config with my React component and send the user data over to the main Electron process?

Thanks

**Comment by redanium** [comment]
Use it in both processes with `require('electron-config')` assuming you are using the **default name( config.json)** but in the main process it has to be after you set the **userData** path.


```
//Main process
...
const Config = require('electron-config');
...
app.setPath("userData", __dirname + "/userData");
const config = new Config();
config.set('xxx','yyy')
...
```
I hope this will help :)

**Comment by redanium** [comment]
refer to this [Developing desktop applications with Electron and React](https://medium.com/@Agro/developing-desktop-applications-with-electron-and-react-40d117d97564)

**Comment by sindresorhus** [comment]
> How do I use electron-config with my React component and send the user data over to the main Electron process?

You don't. As mentioned in the readme, it works in both the main and renderer process, so you just use it exactly as you would have in the main process. The IPC stuff is handled for you.

**Comment by naheller** [comment]
I have a general understanding of using React and Electron -- I just need a little guidance on the specific syntax of calling up electron-config in a React component.

**Comment by sindresorhus** [comment]
See the usage example: https://github.com/sindresorhus/electron-config#usage You require it, initialize it, and then, for example, call `config.get('savedConfigItem')` in a React component when you need that info. If you have a lot of defaults, it can be smart to put it in a separate file so it can be easily required in multiple files: https://github.com/sindresorhus/caprine/blob/6269a983be6e8cafad2a4ab27448fdacb83c9755/config.js

**Comment by bakaa99** [comment]
s

> See the usage example: https://github.com/sindresorhus/electron-config#usage You require it, initialize it, and then, for example, call `config.get('savedConfigItem')` in a React component when you need that info. If you have a lot of defaults, it can be smart to put it in a separate file so it can be easily required in multiple files: https://github.com/sindresorhus/caprine/blob/6269a983be6e8cafad2a4ab27448fdacb83c9755/config.js

i required and initialized the store in the main process. Now if i want to use it in renderer, (react in my case) how do i import that store or do i create a new store?

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/electron-store/issues/15
