### ISSUE TITLE
config.json not found in app dir after using electron-packager

### ISSUE THREAD

**Issue by redanium** [sindresorhus/electron-config#11]
Hi,
Is it possible to give an example on how to use the package after packaging the app with electron-packager ?
(I guess it is in **asar** archive)

Thanks

**Comment by sindresorhus** [comment]
The config is not saved in the app. You wouldn't want the config to go away when the app updates.

Per the readme:

> Config is saved in a JSON file in [`app.getPath('userData')`](http://electron.atom.io/docs/api/app/#appgetpathname).
