### ISSUE TITLE
Getting "Critical dependency" error with webpack

### ISSUE THREAD

**Issue by syonip** [sindresorhus/electron-config#12]
Hi,
I'm using the [electron-vue](https://github.com/SimulatedGREG/electron-vue) boilerplate.
When I add the line `const Config = require('electron-config');` I get the following error:
```
Failed to compile.
./~/conf/index.js
21:27-43 Critical dependency: the request of a dependency is an expression
```

Any idea why?
Thanks

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/electron-config/issues/3
