### ISSUE TITLE
doesn't work with webpack

### ISSUE THREAD

**Issue by steambap** [sindresorhus/electron-config#3]
If I require this module in webpack, it will break webpack because of this line
`const parentDir = path.dirname(module.parent.filename);`

Is there any way to make it work webpack, maybe refer to the global.module instead of just module?

I'm using:

- electron-config: 0.2.1
- electron: 1.4.1
- webpack: 1.13.2

**Comment by sindresorhus** [comment]
It's the inverse: Webpack doesn't work with this module. Open an issue on the Webpack repo.

**Comment by jamesmacfie8i** [comment]
@steambap Not sure if the fix I used will work for you, but adding this into your webpack.config may help:

``` js
externals: [{
  'electron-config': 'electron-config'
}]
```

**Comment by jaxgeller** [comment]
Sorry to comment after being closed. Adding the externals like above and `output.libraryTarget= 'commonjs2'` seems to do the trick. I hope this helps.

**Comment by danielnieto** [comment]
solutions above didn't work for me, but I did this: 

`
externals: [{
    'electron-config': 'require("electron-config")'
}]
`

I didn't have to add anything else, if it's useful here's my webpack.config.js:
(I'm my project I'm using vue.js)

`
/* eslint strict: 0 */
'use strict';

const path = require('path');
const webpack = require('webpack');

let options ={
watch: true,
target: "electron",
externals: {
    'electron': 'require("electron")',
    'net': 'require("net")',
    'remote': 'require("remote")',
    'shell': 'require("shell")',
    'app': 'require("app")',
    'ipc': 'require("ipc")',
    'fs': 'require("fs")',
    'buffer': 'require("buffer")',
    'system': '{}',
    'file': '{}',
    'electron-config': 'require("electron-config")'
},
  module: {
    loaders: [{
      test: /\.jsx?$/,
      loaders: [],
      exclude: /node_modules/,
    }]
  },
  output: {
    path: path.join(__dirname, 'app/build'),
    publicPath: path.join(__dirname, 'src'),
    filename: 'bundle.js',
  },
  resolve: {
    extensions: ['', '.js', '.jsx'],
    packageMains: ['webpack', 'browser', 'web', 'browserify', ['jam', 'main'], 'main'],
    alias: {vue: 'vue/dist/vue.js'}
  },
  entry: [
    './app/js/index',
  ],
  debug: true,

};

module.exports = options;

`

**Comment by akashnimare** [comment]
@jaxgeller @jamesmacfie8i this works perfectly - 
``` javascript 
module.exports = {
    target: 'node',
    externals: [{
      'electron-config': 'electron-config'
    }],
    output: {
    	libraryTarget : 'commonjs2'
    }
};

**Comment by komplexb** [comment]
Hey @danielnieto was there a particular issue you were trying to solve why you have all those other externals?
```
externals: {
    'electron': 'require("electron")',
    'net': 'require("net")',
    'remote': 'require("remote")',
    'shell': 'require("shell")',
    'app': 'require("app")',
    'ipc': 'require("ipc")',
    'fs': 'require("fs")',
    'buffer': 'require("buffer")',
    'system': '{}',
    'file': '{}',
    'electron-config': 'require("electron-config")'
},
```

**Comment by komplexb** [comment]
Hey @jamesmacfie8i I tried https://github.com/sindresorhus/electron-config/issues/3#issuecomment-249478868 but now I get `Uncaught ReferenceError: electron is not defined`, any thoughts?

**Comment by komplexb** [comment]
Hey @steambap did you get https://github.com/sindresorhus/electron-config/issues/3#issue-179019834 solved?

**Comment by safinn** [comment]
@komplexb When I exclude this module in the webpack config I also get the issue with electron cannot be found. Did you get this working?

**Comment by komplexb** [comment]
@safinn I think this is what I did: https://github.com/komplexb/notifyer-electron/blob/master/config.js#L25

**Comment by sallar** [comment]
For people who come here, you have to add `conf` to the `externals` array as well.

**Comment by nicolabortignon** [comment]
@sallar would you please list exactly the steps you need to take to make this lib working with webpack?

**Comment by sallar** [comment]
@nicolabortignon In your webpack config:

``` js
module.exports = {
  ...
  externals: ['conf']
};
```
More info: https://webpack.js.org/configuration/externals/

**Comment by nicolabortignon** [comment]
@sallar sorry, but not 100% sure here.

I'm using this boilerplate: https://github.com/chentsulin/electron-react-boilerplate

And in this file: https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.base.js

at line 10, I did replace with: 
`  externals: ['conf', Object.keys(externals || {})]  ,`


This doesn't work. Any idea why?

**Comment by ClementParis016** [comment]
`output.libraryTarget` and `externals` aren't of any help, I did look at a few related issues but it gets quite complicated, I've no idea how this can be solved...

**Comment by alexbrazier** [comment]
I got this working by adding `electron-store` to externals. `externals: ['electron-store']`

@nicolabortignon Using the boilerplate you can change: `import { dependencies as externals } from './app/package.json';` to `import { dependencies as externals } from './package.json';` to make it work

**Comment by sgehrman** [comment]
same problem, nothing works, why can't this work with webpack?

**Comment by mdings** [comment]
@sgehrman are you sure you're using the right package name? If you did a recent install then the above package names should be renamed to `electron-store`, like so:

`externals: [{ 'electron-store': 'require("electron-store")' }]`

**Comment by framerate** [comment]
> It's the inverse: Webpack doesn't work with this module. Open an issue on the Webpack repo.

FYI: It's almost 2018 and this is still broken, if you end up here like I did.

> same problem, nothing works, why can't this work with webpack?

Because @sindresorhus doesn't use webpack, I guess.

**Comment by sindresorhus** [comment]
Please show your frustration on the webpack issue tracker: https://github.com/webpack/webpack/issues/196
