### ISSUE TITLE
Ability to register listeners for config changes?

### ISSUE THREAD

**Issue by callodacity** [sindresorhus/electron-config#5]
Like the title says. 
Could this be done with node's `events` without too much effort? Or could there be a way to easily implement `onChange` event hooks?

**Comment by sindresorhus** [comment]
Why? Can you provide some realistic use-cases?

**Comment by SamVerschueren** [comment]
If, and only if, there seem to be use cases for this, I would use an observable for that.

**Comment by callodacity** [comment]
You're right, I ended up just using an `EventEmitter` instead. 

Nice suggestion with the observable too 👍
