### ISSUE TITLE
When to use sindresorhus/electron-config or sindresorhus/conf?

### ISSUE THREAD

**Issue by johanges** [sindresorhus/electron-config#6]
There is a substantial overlap between **sindresorhus/electron-config** and **sindresorhus/conf**, not the least of they being by the same author.

(There is also a **yeoman/configstore** project, but it appears deprecated. Is that correct?)

**Comment by sindresorhus** [comment]
`electron-config` is for Electron and uses Electron provided paths (read the code all you'll see). `conf` is for anything.

Regarding `configstore`, read this: https://github.com/sindresorhus/conf#how-is-this-different-from-configstore
