### ISSUE TITLE
Default usage not working

### ISSUE THREAD

**Issue by yannbertrand** [sindresorhus/electron-config#8]
Just tried the default usage from the readme. I get this error:

```
/Users/yann/Development/electron-config-test/node_modules/electron-config/index.js:8
		opts.cwd = (electron.app || electron.remote.app).getPath('userData');
		                                           ^

TypeError: Cannot read property 'app' of undefined
    at ElectronConfig (/Users/yann/Development/electron-config-test/node_modules/electron-config/index.js:8:46)
    at Object.<anonymous> (/Users/yann/Development/electron-config-test/index.js:3:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

By the way, why is not `electron` a dependency in `electron-config` (got `Cannot find module 'electron'` error when electron not installed)?

https://gist.github.com/yannbertrand/c2f6f246df2c35e45a2bba7237688da3
node@7.3.0
npm@3.10.10

**Comment by SamVerschueren** [comment]
Are you using it inside an Electron application? It seems like you are just using it in a regular node app.

**Comment by yannbertrand** [comment]
Yep! I just wanted to try the default usage.

I've also tried by requiring `electron` before `electron-config`, same result

**Comment by SamVerschueren** [comment]
It has to be used inside an Electron app. If you Are looking for a standalone version, have a look at [conf](https://github.com/sindresorhus/conf).

**Comment by yannbertrand** [comment]
Could the default usage make this clearer? I'm still not sure what the minimum setup is to use it

**Comment by SamVerschueren** [comment]
The thing is, what are you trying to do? What is your use case. If you don't know what Electron is, or if you aren't building an Electron app, don't look at the module. The readme is pretty clear imo if you know what Electron is. Not sure what can be improved.

**Comment by yannbertrand** [comment]
I don't have a particular use case. I just wanted to give the module a try, copy-paste what I found in the readme but resulted in an error. I personally think the default usage should contain some working code, don't you agree?

**Comment by sindresorhus** [comment]
@yannbertrand The code is working perfectly. You're just running it with `node file.js`, which @SamVerschueren is trying to tell you is not how it's supposed to be used. This is an Electron module supposed to be used in an Electron app. It works fine if you run your file with `electron file.js` (Requires `npm i -g electron` first). It will also not work if you try to run with Python: `python file.js`.

**Comment by yannbertrand** [comment]
Oh! I see. Sorry about the misunderstanding
